const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const docsRoot = path.join(repoRoot, 'docs');
const subpageRoot = path.join(docsRoot, 'subpage');
const sidebarPath = path.join(docsRoot, '_sidebar.md');

const markdownExtensions = new Set(['.md']);
const ignoredDirs = new Set(['images']);

function naturalCompare(left, right) {
  return left.localeCompare(right, 'zh-Hans-CN', { numeric: true, sensitivity: 'base' });
}

function toPosix(filePath) {
  return filePath.split(path.sep).join('/');
}

function readTitleFromMarkdown(filePath, fallback) {
  const content = fs.readFileSync(filePath, 'utf8');
  const heading = content.match(/^#\s+(.+)$/m);
  if (heading && heading[1]) {
    return heading[1].trim();
  }

  return fallback;
}

function listDirectories(dirPath) {
  return fs.readdirSync(dirPath, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !ignoredDirs.has(entry.name))
    .map((entry) => entry.name)
    .sort(naturalCompare);
}

function listMarkdownFiles(dirPath) {
  return fs.readdirSync(dirPath, { withFileTypes: true })
    .filter((entry) => entry.isFile() && markdownExtensions.has(path.extname(entry.name)) && !entry.name.startsWith('_'))
    .map((entry) => entry.name)
    .sort(naturalCompare);
}

function makeSidebarLink(targetPath) {
  return `./${toPosix(path.relative(docsRoot, targetPath))}`;
}

function buildDirectoryTree(dirPath, indentLevel) {
  const lines = [];
  const directories = listDirectories(dirPath);
  const markdownFiles = listMarkdownFiles(dirPath);
  const indent = '  '.repeat(indentLevel);

  for (const fileName of markdownFiles) {
    const filePath = path.join(dirPath, fileName);
    const label = readTitleFromMarkdown(filePath, path.basename(fileName, '.md'));
    lines.push(`${indent}- [${label}](${makeSidebarLink(filePath)})`);
  }

  for (const directoryName of directories) {
    const nestedDirPath = path.join(dirPath, directoryName);
    const nestedLines = buildDirectoryTree(nestedDirPath, indentLevel + 1);
    if (nestedLines.length === 0) {
      continue;
    }

    lines.push(`${indent}- ${directoryName}`);
    lines.push(...nestedLines);
  }

  return lines;
}

function buildTopicSection(topicDirName) {
  const topicDirPath = path.join(subpageRoot, topicDirName);
  const topicIndexName = `_${topicDirName}.md`;
  const topicIndexPath = path.join(topicDirPath, topicIndexName);

  if (!fs.existsSync(topicIndexPath)) {
    return [];
  }

  const topicLabel = readTitleFromMarkdown(topicIndexPath, topicDirName);
  const lines = [`- [${topicLabel}](${makeSidebarLink(topicIndexPath)})`];
  const subsubpageDirPath = path.join(topicDirPath, 'subsubpage');

  if (fs.existsSync(subsubpageDirPath)) {
    lines.push(...buildDirectoryTree(subsubpageDirPath, 1));
  }

  return lines;
}

function buildSidebar() {
  const topicDirs = listDirectories(subpageRoot);
  const sections = topicDirs
    .map(buildTopicSection)
    .filter((lines) => lines.length > 0)
    .map((lines) => lines.join('\n'));

  return [
    '<!-- AUTO-GENERATED by scripts/generate-sidebar.js. Do not edit manually. -->',
    ...sections,
    '',
  ].join('\n\n');
}

fs.writeFileSync(sidebarPath, buildSidebar(), 'utf8');
console.log(`Generated ${path.relative(repoRoot, sidebarPath)}`);